# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Wedding Planner CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -Dspring.datasource.url=${{ secrets.DB_URL }} -Dspring.datasource.username=${{ secrets.DB_USERNAME }} -Dspring.datasource.password=${{ secrets.DB_PASSWORD }}
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      env:
        # Store sensitive information as secrets
        SPRING_DATASOURCE_URL: ${{ secrets.DATABASE_URL }}
        SPRING_DATASOURCE_USERNAME: ${{ secrets.DATABASE_USER }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      with:
        image: smit814/wedding-planning-images
        tags: v0.1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
